FROM openjdk:13-jdk-alpine

VOLUME /tmp

EXPOSE 7171

ARG JAR_FILE=target/solution-0.0.1-SNAPSHOT.jar

ADD ${JAR_FILE} solution-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/solution-0.0.1-SNAPSHOT.jar"]